public class Calculation {
    public integer add(integer a, integer b){
        Integer sum = a + b;
        return sum; 
    }
    public integer subtract(integer a, integer b){
        Integer sub = a - b;
        return sub;
    }
    public integer multiply(integer a, integer b){
        Integer mul = a * b;
        return mul;
    }
    public integer divide(integer a, integer b){
        Integer div = a / b;
        return div;
    }
}