public class SalesforceDeveloper {
    public void myFirstCode() {
        String city = 'Paris';
        String movie = 'The Green Mile';
        String season = 'Spring';

        System.debug(city);
        System.debug(movie);
        System.debug(season);

    }

    public void myFavorites(){
        integer myNum = 8;
        string myCity = 'Istanbul';
        System.debug(myNum);
        System.debug(myCity);

        System.debug('Favori Numaram -> ' + myNum + ' ve ' + 'Favori Şehrim -> ' + myCity);
    }
}